export type DocChapter = {
  id: string; group: string; title: string; english: string; summary: string;
  concepts: string[]; algorithms: string[]; equation?: string; lab: string;
};

export const docChapters: DocChapter[] = [
  {id:"signals",group:"مبانی",title:"سیگنال و سیستم",english:"Signals & Systems",summary:"سیگنال نمایش ریاضی اطلاعات است؛ سیستم آن را تبدیل می‌کند. پیوسته/گسسته، تناوبی/نامتناوب، انرژی/توان و علی/غیرعلی پایهٔ تحلیل‌اند.",concepts:["دامنه، فاز، فرکانس و دوره","سیستم‌های خطی و تغییرناپذیر با زمان (LTI)","کانولوشن و پاسخ ضربه","توان، انرژی، RMS و هم‌بستگی"],algorithms:["Convolution","Correlation","RMS","Autocorrelation"],equation:"y(t)=x(t)*h(t)",lab:"موج سینوسی و نویز"},
  {id:"fourier",group:"مبانی",title:"حوزه فرکانس و فوریه",english:"Fourier Analysis",summary:"تبدیل فوریه یک سیگنال را به مؤلفه‌های فرکانسی تجزیه می‌کند. DFT نسخهٔ گسسته و FFT روش سریع محاسبهٔ آن است.",concepts:["Fourier Series و Fourier Transform","DFT، IDFT، FFT و IFFT","Spectral Leakage و Windowing","Gibbs، پهنای باند و PSD"],algorithms:["FFT","DFT","Welch PSD","Hann/Hamming/Blackman"],equation:"X(f)=∫x(t)e^{-j2πft}dt",lab:"تحلیل FFT"},
  {id:"sampling",group:"دیجیتال‌سازی",title:"نمونه‌برداری",english:"Sampling",summary:"سیگنال آنالوگ در زمان‌های مشخص اندازه‌گیری می‌شود. برای جلوگیری از Aliasing نرخ نمونه باید از دو برابر بیشترین فرکانس مؤثر بزرگ‌تر باشد.",concepts:["Uniform و Non-uniform Sampling","قضیه Nyquist–Shannon","Aliasing و Anti-alias Filter","Sample-and-Hold و Jitter"],algorithms:["Uniform Sampling","Decimation","Interpolation","Resampling"],equation:"fₛ > 2fₘₐₓ",lab:"Nyquist و Aliasing"},
  {id:"quantization",group:"دیجیتال‌سازی",title:"کوانتیزاسیون و PCM",english:"Quantization & PCM",summary:"دامنهٔ نمونه‌ها به تعداد محدودی سطح نگاشت و سپس به بیت تبدیل می‌شود. رزولوشن بالاتر خطای کوانتیزاسیون را کاهش می‌دهد.",concepts:["Uniform و Non-uniform Quantization","μ-law و A-law","PCM، DPCM، Delta و ADPCM","SQNR و خطای کوانتیزاسیون"],algorithms:["PCM","DPCM","ADPCM","Delta Modulation"],equation:"L=2ᵇ",lab:"زنجیره PCM"},
  {id:"source",group:"کدگذاری",title:"کدگذاری منبع",english:"Source Coding",summary:"افزونگی آماری حذف می‌شود تا داده با بیت کمتر نمایش داده شود؛ کدهای بدون اتلاف باید قابلیت بازیابی دقیق داشته باشند.",concepts:["Entropy و Information Content","Prefix-free Codes","Lossless و Lossy Compression","نسبت فشرده‌سازی"],algorithms:["Huffman","Arithmetic Coding","RLE","LZW"],equation:"H(X)=-Σp(x)log₂p(x)",lab:"فشرده‌سازی هافمن"},
  {id:"channel-coding",group:"کدگذاری",title:"کدگذاری کانال",english:"Error Control Coding",summary:"بیت‌های افزونه برای کشف یا اصلاح خطا افزوده می‌شوند تا لینک در حضور نویز قابل اعتماد بماند.",concepts:["Hamming Distance و Syndrome","Block و Convolutional Codes","Hard/Soft Decision","Coding Gain و نرخ کد"],algorithms:["Parity","Hamming","CRC","Reed–Solomon","Turbo","LDPC","Polar"],equation:"R=k/n",lab:"Hamming روی AWGN"},
  {id:"line",group:"ارسال Baseband",title:"Line Coding و Scrambling",english:"Baseband Signaling",summary:"بیت‌ها به سطح ولتاژ یا پالس تبدیل می‌شوند. انتخاب کد روی مؤلفه DC، پهنای باند و بازیابی Clock اثر دارد.",concepts:["DC Balance و Self-clocking","Run Length و Baseline Wander","Scrambling الگوهای طولانی صفر","چگالی گذار و پهنای باند"],algorithms:["NRZ-L/I","RZ","Manchester","AMI","MLT-3","B8ZS","HDB3"],lab:"مقایسه Line Code"},
  {id:"pulse",group:"ارسال Baseband",title:"شکل‌دهی پالس",english:"Pulse Shaping",summary:"فیلتر فرستنده پهنای باند را محدود و تداخل بین سمبل‌ها را کنترل می‌کند. معیار Nyquist امکان نمونه‌برداری بدون ISI را می‌دهد.",concepts:["ISI و Eye Diagram","Nyquist Pulse Criterion","Roll-off Factor","Matched Filtering"],algorithms:["Raised Cosine","Root Raised Cosine","Gaussian","Rectangular Pulse"],equation:"BW≈Rₛ(1+α)/2",lab:"چشم و RRC"},
  {id:"modulation",group:"مدولاسیون",title:"مدولاسیون دیجیتال",english:"Digital Modulation",summary:"بیت‌ها روی دامنه، فرکانس یا فاز حامل نگاشت می‌شوند. بهره‌وری طیفی بالاتر معمولاً حساسیت بیشتری به نویز دارد.",concepts:["Symbol Mapping و Gray Coding","Constellation و Decision Regions","Eb/N0، BER و Spectral Efficiency","Coherent و Non-coherent"],algorithms:["ASK","FSK","BPSK","QPSK","8-PSK","16/64/256-QAM"],equation:"η=Rᵦ/B",lab:"صورت‌فلکی QAM"},
  {id:"multiplex",group:"مدولاسیون",title:"Multiplexing و Multiple Access",english:"Sharing the Medium",summary:"چند جریان با تقسیم زمان، فرکانس، طول موج یا کد روی یک بستر مشترک حمل می‌شوند.",concepts:["Guard Interval و Orthogonality","Resource Grid","Near–far Problem","Cyclic Prefix"],algorithms:["TDM","FDM","WDM","CDMA","OFDM","OFDMA"],lab:"OFDM چندحاملی"},
  {id:"channel",group:"کانال",title:"مدل کانال و نویز",english:"Channel Models",summary:"محیط انتقال دامنه و فاز را تغییر می‌دهد و نویز اضافه می‌کند. مدل درست کانال برای طراحی گیرنده حیاتی است.",concepts:["AWGN و SNR","Path Loss و Shadowing","Rayleigh/Rician Fading","Multipath، Delay Spread و Doppler"],algorithms:["AWGN","Rayleigh","Rician","FIR Multipath","Free-space Path Loss"],equation:"C=B log₂(1+S/N)",lab:"Fading و Equalizer"},
  {id:"sync",group:"گیرنده",title:"هم‌زمان‌سازی",english:"Synchronization",summary:"گیرنده باید مرز سمبل، فرکانس و فاز حامل و شروع Frame را از سیگنال دریافتی بازیابی کند.",concepts:["Clock و Symbol Timing Recovery","Carrier Frequency/Phase Recovery","Preamble و Frame Sync","PLL و Timing Error Detector"],algorithms:["Gardner","Mueller–Müller","Costas Loop","Correlation Sync"],lab:"Carrier Recovery"},
  {id:"receiver",group:"گیرنده",title:"آشکارسازی و رمزگشایی",english:"Detection & Decoding",summary:"Matched Filter نسبت سیگنال به نویز را در لحظه تصمیم بیشینه می‌کند؛ سپس Detector و Decoder بیت محتمل را بازیابی می‌کنند.",concepts:["Threshold، ML و MAP Detection","Matched Filter و Correlator","Viterbi و Syndrome Decoding","Iterative Decoding و LLR"],algorithms:["Envelope Detector","ML/MAP","Viterbi","Berlekamp–Massey","LDPC Iterative"],lab:"گیرنده BPSK"},
  {id:"reconstruction",group:"گیرنده",title:"بازسازی و DAC",english:"Reconstruction",summary:"نمونه‌های دیجیتال با DAC و فیلتر بازسازی به سیگنال پیوسته تبدیل می‌شوند؛ تصاویر طیفی باید حذف شوند.",concepts:["Zero-order Hold","Reconstruction Low-pass Filter","Oversampling","Smoothing و Analog Output"],algorithms:["DAC","Low-pass FIR/IIR","Interpolation","Smoothing"],lab:"بازسازی خروجی"},
  {id:"embedded",group:"Embedded",title:"میکروکنترلر و DSP بلادرنگ",english:"Embedded Signal Systems",summary:"در سیستم Embedded سیگنال از سنسور و ADC وارد می‌شود، با DMA پردازش و از طریق گذرگاه یا PWM/DAC خارج می‌شود.",concepts:["ADC Resolution، Reference و Sample Timer","Interrupt، DMA و Double Buffer","Fixed-point DSP و محدودیت حافظه","Latency، Throughput و Real-time Deadline"],algorithms:["ADC","PWM","DMA","Fixed-point FIR/FFT","Timer Capture"],equation:"Tₛ=1/fₛ",lab:"Sensor → ADC → DSP"},
  {id:"buses",group:"Embedded",title:"UART، SPI و I²C",english:"Digital Interfaces",summary:"گذرگاه‌ها نمونه‌ها و فرمان‌ها را بین MCU، سنسور و مبدل منتقل می‌کنند؛ انتخاب آن‌ها تابع سرعت، سیم‌کشی و توپولوژی است.",concepts:["UART Start/Stop و Baud Rate","SPI Clock/Phase/Polarity","I²C Addressing و Open-drain","Framing، Buffering و Error Handling"],algorithms:["UART","SPI","I²C","Manchester Telemetry"],lab:"UART Telemetry"},
];

export const docGroups = [...new Set(docChapters.map((chapter) => chapter.group))];
